source 'http://rubygems.org'

gem 'rails', '5.0.0.1'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'

gem 'rspec'
gem 'rspec-rails'
gem 'database_cleaner'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
